name: Update Legal Services Sheet

on:
  # schedule:
  #   # Run at 8:30 AM PT (15:30 UTC) - Before most services open
  #   - cron: '30 15 * * *'
  #   # Run at 12:00 PM PT (19:00 UTC) - Midday update
  #   - cron: '0 19 * * *'  
  #   # Run at 6:00 PM PT (1:00 UTC next day) - End of day update
  #   - cron: '0 1 * * *'   
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # Explicitly grant write permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credential.json

      - name: Run updater script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
        
      - name: Commit updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          
      - name: Push changes
        run: git push origin HEAD:main
