name: Update Legal Services Sheet

on:
  schedule:
    - cron: '0 9 * * 1'  # 9 AM UTC every Monday (2 AM PST/1 AM PDT)
  workflow_dispatch:  # Optional: Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credential.json

      - name: Run updater script
        run: python main.py

      - name: Commit updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main